config/routes.rb
Rails.application.routes.draw do
  namespace :company do
    root to: 'dashboard#index'
    resources :payments, only: :update
  end

  namespace :investor do
    root to: 'dashboard#index'
    resources :payments, only: :index
    resources :loans, only: [:new, :create, :destroy]
  end

  root to: 'home#index'

  devise_for :companies,
             controllers: { sessions: 'companies/sessions',
                            registrations: 'companies/registrations' }
  devise_for :investors,
             controllers: { sessions: 'investors/sessions',
                            registrations: 'investors/registrations' }
end

app/models/accounts/company.rb
class Company < Account
  has_many :loans
  has_many :payments, through: :loans
end

app/controllers/companies/registrations_controller.rb
class Companies::RegistrationsController < Devise::RegistrationsController
  # GET /companies/sign_up
  def new
    current_investor ? (redirect_to root_path) : super
  end
end

app/controllers/companies/sessions_controller.rb
class Companies::SessionsController < Devise::SessionsController
  # GET /companies/sign_in
  def new
    current_investor ? (redirect_to root_path) : super
  end

  def create
    super
    session[:current_account_id] = current_company.id
  end

  def destroy
    super
    session[:current_account_id] = nil
  end
end

app/controllers/company/dashboard_controller.rb
class Company::DashboardController < ApplicationController
  before_action :authenticate_company!

  def index
    @loans = Loan.where(company: current_company)
  end
end

app/controllers/company/payments_controller.rb
class Company::PaymentsController < ApplicationController
  before_action :authenticate_company!

  # TODO: write normal controller
  def update
    @payment = Payment.find(params[:id])
    @payment.delayed = params[:delayed]
    @payment.repayment = params[:repayment]
    @payment.paid = true
    @payment.save

    redirect_to company_root_path
  end
end

app/controllers/investor/dashboard_controller.rb
class Investor::DashboardController < InvestorController
  before_action :authenticate_investor!

  def index
    @loans = Loan.where(investor: current_investor)
  end
end

app/views/company/dashboard/index.html.slim
h1 Полученные займы
table.table
  thead
    th Инвестор
    th Сумма
    th Срок, мес.
    th Состояние
    th colspan=1
  tbody
    - @loans.each do |l|
      tr
        td = l.investor.name
        td = l.amount
        td = l.time
        td = l.state
        td
          - if l.payments.unpaid.count > 0
            .btn-group
              button.btn.btn-default.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
                | Действия
                span.caret
              ul.dropdown-menu.dropdown-menu-right
                li
                  = link_to 'Погасить ближайший платёж', company_payment_path(l.following_payment), method: :put
                li
                  = link_to 'Погасить ближайший платёж с просрочкой', company_payment_path(l.following_payment, delayed: true), method: :put
                li
                  = link_to 'Погасить остаток досрочно', company_payment_path(l.following_payment, repayment: true), method: :put