config/routes.rb
Rails.application.routes.draw do
  namespace :company do
    root to: 'dashboard#index'
    resources :payments, only: :update
  end

  namespace :investor do
    root to: 'dashboard#index'
    resources :payments, only: :index
    resources :loans, only: [:new, :create, :destroy]
  end

  root to: 'home#index'

  devise_for :companies,
             controllers: { sessions: 'companies/sessions',
                            registrations: 'companies/registrations' }
  devise_for :investors,
             controllers: { sessions: 'investors/sessions',
                            registrations: 'investors/registrations' }
end

app/views/layouts/_head.html.slim
title Калькулятор доходности
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      = link_to 'Калькулятор доходности', root_path, class: 'navbar-brand'
    nav.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if @_current_account
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              = @_current_account.email
              span.caret
            ul.dropdown-menu
              li
                = link_to 'Дэшборд', dashboard_path
              li.divider role="separator"
              li
                = link_to 'Выйти', destroy_session_path(@_current_account), method: :delete
        - else
          li
            p.navbar-text
              = 'Войти как '
              = link_to 'компания', new_company_session_path
              = ' или '
              = link_to 'инвестор', new_investor_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    = render partial: 'layouts/head'
  body
    = render 'layouts/header'
    .container-fluid.main-container
      = yield

app/views/layouts/investor.html.slim
doctype html
html
  head
    = render partial: 'layouts/head'
  body
    = render 'layouts/header'
    .container-fluid.main-container
      .row
        .col-sm-3.col-md-2.sidebar
          ul.nav.nav-sidebar
            li class=( active_link(investor_root_path) )
              = link_to 'Дэшборд', investor_root_path
            li class=( active_link(investor_payments_path) )
              = link_to 'История платежей', investor_payments_path
            li class=( active_link(new_investor_loan_path) )
              = link_to 'Новые инвестиции', new_investor_loan_path
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield
    = console